// This file was auto generated by StructMembers.py, 
// when making changes to this file, please do it through that script to preserve them

#define STRUCT_MEMBER_TYPES_1(Struct, _m0, _n0) \
	std::move(std::vector<VirtualType::Type>(\
	{\
		VirtualType::type<decltype(Struct::_m0)>(), \
	}))


#define STRUCT_MEMBER_TYPES_2(Struct, _m0, _n0, _m1, _n1) \
	std::move(std::vector<VirtualType::Type>(\
	{\
		VirtualType::type<decltype(Struct::_m0)>(), \
		VirtualType::type<decltype(Struct::_m1)>(), \
	}))


#define STRUCT_MEMBER_TYPES_3(Struct, _m0, _n0, _m1, _n1, _m2, _n2) \
	std::move(std::vector<VirtualType::Type>(\
	{\
		VirtualType::type<decltype(Struct::_m0)>(), \
		VirtualType::type<decltype(Struct::_m1)>(), \
		VirtualType::type<decltype(Struct::_m2)>(), \
	}))


#define STRUCT_MEMBER_TYPES_4(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3) \
	std::move(std::vector<VirtualType::Type>(\
	{\
		VirtualType::type<decltype(Struct::_m0)>(), \
		VirtualType::type<decltype(Struct::_m1)>(), \
		VirtualType::type<decltype(Struct::_m2)>(), \
		VirtualType::type<decltype(Struct::_m3)>(), \
	}))


#define STRUCT_MEMBER_TYPES_5(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4) \
	std::move(std::vector<VirtualType::Type>(\
	{\
		VirtualType::type<decltype(Struct::_m0)>(), \
		VirtualType::type<decltype(Struct::_m1)>(), \
		VirtualType::type<decltype(Struct::_m2)>(), \
		VirtualType::type<decltype(Struct::_m3)>(), \
		VirtualType::type<decltype(Struct::_m4)>(), \
	}))


#define STRUCT_MEMBER_TYPES_6(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5) \
	std::move(std::vector<VirtualType::Type>(\
	{\
		VirtualType::type<decltype(Struct::_m0)>(), \
		VirtualType::type<decltype(Struct::_m1)>(), \
		VirtualType::type<decltype(Struct::_m2)>(), \
		VirtualType::type<decltype(Struct::_m3)>(), \
		VirtualType::type<decltype(Struct::_m4)>(), \
		VirtualType::type<decltype(Struct::_m5)>(), \
	}))


#define STRUCT_MEMBER_TYPES_7(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6) \
	std::move(std::vector<VirtualType::Type>(\
	{\
		VirtualType::type<decltype(Struct::_m0)>(), \
		VirtualType::type<decltype(Struct::_m1)>(), \
		VirtualType::type<decltype(Struct::_m2)>(), \
		VirtualType::type<decltype(Struct::_m3)>(), \
		VirtualType::type<decltype(Struct::_m4)>(), \
		VirtualType::type<decltype(Struct::_m5)>(), \
		VirtualType::type<decltype(Struct::_m6)>(), \
	}))


#define STRUCT_MEMBER_TYPES_8(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7) \
	std::move(std::vector<VirtualType::Type>(\
	{\
		VirtualType::type<decltype(Struct::_m0)>(), \
		VirtualType::type<decltype(Struct::_m1)>(), \
		VirtualType::type<decltype(Struct::_m2)>(), \
		VirtualType::type<decltype(Struct::_m3)>(), \
		VirtualType::type<decltype(Struct::_m4)>(), \
		VirtualType::type<decltype(Struct::_m5)>(), \
		VirtualType::type<decltype(Struct::_m6)>(), \
		VirtualType::type<decltype(Struct::_m7)>(), \
	}))


#define STRUCT_MEMBER_TYPES_9(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8) \
	std::move(std::vector<VirtualType::Type>(\
	{\
		VirtualType::type<decltype(Struct::_m0)>(), \
		VirtualType::type<decltype(Struct::_m1)>(), \
		VirtualType::type<decltype(Struct::_m2)>(), \
		VirtualType::type<decltype(Struct::_m3)>(), \
		VirtualType::type<decltype(Struct::_m4)>(), \
		VirtualType::type<decltype(Struct::_m5)>(), \
		VirtualType::type<decltype(Struct::_m6)>(), \
		VirtualType::type<decltype(Struct::_m7)>(), \
		VirtualType::type<decltype(Struct::_m8)>(), \
	}))


#define STRUCT_MEMBER_TYPES_10(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9) \
	std::move(std::vector<VirtualType::Type>(\
	{\
		VirtualType::type<decltype(Struct::_m0)>(), \
		VirtualType::type<decltype(Struct::_m1)>(), \
		VirtualType::type<decltype(Struct::_m2)>(), \
		VirtualType::type<decltype(Struct::_m3)>(), \
		VirtualType::type<decltype(Struct::_m4)>(), \
		VirtualType::type<decltype(Struct::_m5)>(), \
		VirtualType::type<decltype(Struct::_m6)>(), \
		VirtualType::type<decltype(Struct::_m7)>(), \
		VirtualType::type<decltype(Struct::_m8)>(), \
		VirtualType::type<decltype(Struct::_m9)>(), \
	}))


#define STRUCT_MEMBER_TYPES_11(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10) \
	std::move(std::vector<VirtualType::Type>(\
	{\
		VirtualType::type<decltype(Struct::_m0)>(), \
		VirtualType::type<decltype(Struct::_m1)>(), \
		VirtualType::type<decltype(Struct::_m2)>(), \
		VirtualType::type<decltype(Struct::_m3)>(), \
		VirtualType::type<decltype(Struct::_m4)>(), \
		VirtualType::type<decltype(Struct::_m5)>(), \
		VirtualType::type<decltype(Struct::_m6)>(), \
		VirtualType::type<decltype(Struct::_m7)>(), \
		VirtualType::type<decltype(Struct::_m8)>(), \
		VirtualType::type<decltype(Struct::_m9)>(), \
		VirtualType::type<decltype(Struct::_m10)>(), \
	}))


#define STRUCT_MEMBER_TYPES_12(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11) \
	std::move(std::vector<VirtualType::Type>(\
	{\
		VirtualType::type<decltype(Struct::_m0)>(), \
		VirtualType::type<decltype(Struct::_m1)>(), \
		VirtualType::type<decltype(Struct::_m2)>(), \
		VirtualType::type<decltype(Struct::_m3)>(), \
		VirtualType::type<decltype(Struct::_m4)>(), \
		VirtualType::type<decltype(Struct::_m5)>(), \
		VirtualType::type<decltype(Struct::_m6)>(), \
		VirtualType::type<decltype(Struct::_m7)>(), \
		VirtualType::type<decltype(Struct::_m8)>(), \
		VirtualType::type<decltype(Struct::_m9)>(), \
		VirtualType::type<decltype(Struct::_m10)>(), \
		VirtualType::type<decltype(Struct::_m11)>(), \
	}))


#define STRUCT_MEMBER_TYPES_13(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12) \
	std::move(std::vector<VirtualType::Type>(\
	{\
		VirtualType::type<decltype(Struct::_m0)>(), \
		VirtualType::type<decltype(Struct::_m1)>(), \
		VirtualType::type<decltype(Struct::_m2)>(), \
		VirtualType::type<decltype(Struct::_m3)>(), \
		VirtualType::type<decltype(Struct::_m4)>(), \
		VirtualType::type<decltype(Struct::_m5)>(), \
		VirtualType::type<decltype(Struct::_m6)>(), \
		VirtualType::type<decltype(Struct::_m7)>(), \
		VirtualType::type<decltype(Struct::_m8)>(), \
		VirtualType::type<decltype(Struct::_m9)>(), \
		VirtualType::type<decltype(Struct::_m10)>(), \
		VirtualType::type<decltype(Struct::_m11)>(), \
		VirtualType::type<decltype(Struct::_m12)>(), \
	}))


#define STRUCT_MEMBER_TYPES_14(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12, _m13, _n13) \
	std::move(std::vector<VirtualType::Type>(\
	{\
		VirtualType::type<decltype(Struct::_m0)>(), \
		VirtualType::type<decltype(Struct::_m1)>(), \
		VirtualType::type<decltype(Struct::_m2)>(), \
		VirtualType::type<decltype(Struct::_m3)>(), \
		VirtualType::type<decltype(Struct::_m4)>(), \
		VirtualType::type<decltype(Struct::_m5)>(), \
		VirtualType::type<decltype(Struct::_m6)>(), \
		VirtualType::type<decltype(Struct::_m7)>(), \
		VirtualType::type<decltype(Struct::_m8)>(), \
		VirtualType::type<decltype(Struct::_m9)>(), \
		VirtualType::type<decltype(Struct::_m10)>(), \
		VirtualType::type<decltype(Struct::_m11)>(), \
		VirtualType::type<decltype(Struct::_m12)>(), \
		VirtualType::type<decltype(Struct::_m13)>(), \
	}))


#define STRUCT_MEMBER_TYPES_15(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12, _m13, _n13, _m14, _n14) \
	std::move(std::vector<VirtualType::Type>(\
	{\
		VirtualType::type<decltype(Struct::_m0)>(), \
		VirtualType::type<decltype(Struct::_m1)>(), \
		VirtualType::type<decltype(Struct::_m2)>(), \
		VirtualType::type<decltype(Struct::_m3)>(), \
		VirtualType::type<decltype(Struct::_m4)>(), \
		VirtualType::type<decltype(Struct::_m5)>(), \
		VirtualType::type<decltype(Struct::_m6)>(), \
		VirtualType::type<decltype(Struct::_m7)>(), \
		VirtualType::type<decltype(Struct::_m8)>(), \
		VirtualType::type<decltype(Struct::_m9)>(), \
		VirtualType::type<decltype(Struct::_m10)>(), \
		VirtualType::type<decltype(Struct::_m11)>(), \
		VirtualType::type<decltype(Struct::_m12)>(), \
		VirtualType::type<decltype(Struct::_m13)>(), \
		VirtualType::type<decltype(Struct::_m14)>(), \
	}))


#define STRUCT_MEMBER_TYPES_16(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12, _m13, _n13, _m14, _n14, _m15, _n15) \
	std::move(std::vector<VirtualType::Type>(\
	{\
		VirtualType::type<decltype(Struct::_m0)>(), \
		VirtualType::type<decltype(Struct::_m1)>(), \
		VirtualType::type<decltype(Struct::_m2)>(), \
		VirtualType::type<decltype(Struct::_m3)>(), \
		VirtualType::type<decltype(Struct::_m4)>(), \
		VirtualType::type<decltype(Struct::_m5)>(), \
		VirtualType::type<decltype(Struct::_m6)>(), \
		VirtualType::type<decltype(Struct::_m7)>(), \
		VirtualType::type<decltype(Struct::_m8)>(), \
		VirtualType::type<decltype(Struct::_m9)>(), \
		VirtualType::type<decltype(Struct::_m10)>(), \
		VirtualType::type<decltype(Struct::_m11)>(), \
		VirtualType::type<decltype(Struct::_m12)>(), \
		VirtualType::type<decltype(Struct::_m13)>(), \
		VirtualType::type<decltype(Struct::_m14)>(), \
		VirtualType::type<decltype(Struct::_m15)>(), \
	}))


#define STRUCT_MEMBER_OFFSETS_1(Struct, _m0, _n0) \
	std::move(std::vector<size_t>(\
	{\
		offsetof(Struct, Struct::_m0), \
	}))


#define STRUCT_MEMBER_OFFSETS_2(Struct, _m0, _n0, _m1, _n1) \
	std::move(std::vector<size_t>(\
	{\
		offsetof(Struct, Struct::_m0), \
		offsetof(Struct, Struct::_m1), \
	}))


#define STRUCT_MEMBER_OFFSETS_3(Struct, _m0, _n0, _m1, _n1, _m2, _n2) \
	std::move(std::vector<size_t>(\
	{\
		offsetof(Struct, Struct::_m0), \
		offsetof(Struct, Struct::_m1), \
		offsetof(Struct, Struct::_m2), \
	}))


#define STRUCT_MEMBER_OFFSETS_4(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3) \
	std::move(std::vector<size_t>(\
	{\
		offsetof(Struct, Struct::_m0), \
		offsetof(Struct, Struct::_m1), \
		offsetof(Struct, Struct::_m2), \
		offsetof(Struct, Struct::_m3), \
	}))


#define STRUCT_MEMBER_OFFSETS_5(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4) \
	std::move(std::vector<size_t>(\
	{\
		offsetof(Struct, Struct::_m0), \
		offsetof(Struct, Struct::_m1), \
		offsetof(Struct, Struct::_m2), \
		offsetof(Struct, Struct::_m3), \
		offsetof(Struct, Struct::_m4), \
	}))


#define STRUCT_MEMBER_OFFSETS_6(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5) \
	std::move(std::vector<size_t>(\
	{\
		offsetof(Struct, Struct::_m0), \
		offsetof(Struct, Struct::_m1), \
		offsetof(Struct, Struct::_m2), \
		offsetof(Struct, Struct::_m3), \
		offsetof(Struct, Struct::_m4), \
		offsetof(Struct, Struct::_m5), \
	}))


#define STRUCT_MEMBER_OFFSETS_7(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6) \
	std::move(std::vector<size_t>(\
	{\
		offsetof(Struct, Struct::_m0), \
		offsetof(Struct, Struct::_m1), \
		offsetof(Struct, Struct::_m2), \
		offsetof(Struct, Struct::_m3), \
		offsetof(Struct, Struct::_m4), \
		offsetof(Struct, Struct::_m5), \
		offsetof(Struct, Struct::_m6), \
	}))


#define STRUCT_MEMBER_OFFSETS_8(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7) \
	std::move(std::vector<size_t>(\
	{\
		offsetof(Struct, Struct::_m0), \
		offsetof(Struct, Struct::_m1), \
		offsetof(Struct, Struct::_m2), \
		offsetof(Struct, Struct::_m3), \
		offsetof(Struct, Struct::_m4), \
		offsetof(Struct, Struct::_m5), \
		offsetof(Struct, Struct::_m6), \
		offsetof(Struct, Struct::_m7), \
	}))


#define STRUCT_MEMBER_OFFSETS_9(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8) \
	std::move(std::vector<size_t>(\
	{\
		offsetof(Struct, Struct::_m0), \
		offsetof(Struct, Struct::_m1), \
		offsetof(Struct, Struct::_m2), \
		offsetof(Struct, Struct::_m3), \
		offsetof(Struct, Struct::_m4), \
		offsetof(Struct, Struct::_m5), \
		offsetof(Struct, Struct::_m6), \
		offsetof(Struct, Struct::_m7), \
		offsetof(Struct, Struct::_m8), \
	}))


#define STRUCT_MEMBER_OFFSETS_10(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9) \
	std::move(std::vector<size_t>(\
	{\
		offsetof(Struct, Struct::_m0), \
		offsetof(Struct, Struct::_m1), \
		offsetof(Struct, Struct::_m2), \
		offsetof(Struct, Struct::_m3), \
		offsetof(Struct, Struct::_m4), \
		offsetof(Struct, Struct::_m5), \
		offsetof(Struct, Struct::_m6), \
		offsetof(Struct, Struct::_m7), \
		offsetof(Struct, Struct::_m8), \
		offsetof(Struct, Struct::_m9), \
	}))


#define STRUCT_MEMBER_OFFSETS_11(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10) \
	std::move(std::vector<size_t>(\
	{\
		offsetof(Struct, Struct::_m0), \
		offsetof(Struct, Struct::_m1), \
		offsetof(Struct, Struct::_m2), \
		offsetof(Struct, Struct::_m3), \
		offsetof(Struct, Struct::_m4), \
		offsetof(Struct, Struct::_m5), \
		offsetof(Struct, Struct::_m6), \
		offsetof(Struct, Struct::_m7), \
		offsetof(Struct, Struct::_m8), \
		offsetof(Struct, Struct::_m9), \
		offsetof(Struct, Struct::_m10), \
	}))


#define STRUCT_MEMBER_OFFSETS_12(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11) \
	std::move(std::vector<size_t>(\
	{\
		offsetof(Struct, Struct::_m0), \
		offsetof(Struct, Struct::_m1), \
		offsetof(Struct, Struct::_m2), \
		offsetof(Struct, Struct::_m3), \
		offsetof(Struct, Struct::_m4), \
		offsetof(Struct, Struct::_m5), \
		offsetof(Struct, Struct::_m6), \
		offsetof(Struct, Struct::_m7), \
		offsetof(Struct, Struct::_m8), \
		offsetof(Struct, Struct::_m9), \
		offsetof(Struct, Struct::_m10), \
		offsetof(Struct, Struct::_m11), \
	}))


#define STRUCT_MEMBER_OFFSETS_13(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12) \
	std::move(std::vector<size_t>(\
	{\
		offsetof(Struct, Struct::_m0), \
		offsetof(Struct, Struct::_m1), \
		offsetof(Struct, Struct::_m2), \
		offsetof(Struct, Struct::_m3), \
		offsetof(Struct, Struct::_m4), \
		offsetof(Struct, Struct::_m5), \
		offsetof(Struct, Struct::_m6), \
		offsetof(Struct, Struct::_m7), \
		offsetof(Struct, Struct::_m8), \
		offsetof(Struct, Struct::_m9), \
		offsetof(Struct, Struct::_m10), \
		offsetof(Struct, Struct::_m11), \
		offsetof(Struct, Struct::_m12), \
	}))


#define STRUCT_MEMBER_OFFSETS_14(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12, _m13, _n13) \
	std::move(std::vector<size_t>(\
	{\
		offsetof(Struct, Struct::_m0), \
		offsetof(Struct, Struct::_m1), \
		offsetof(Struct, Struct::_m2), \
		offsetof(Struct, Struct::_m3), \
		offsetof(Struct, Struct::_m4), \
		offsetof(Struct, Struct::_m5), \
		offsetof(Struct, Struct::_m6), \
		offsetof(Struct, Struct::_m7), \
		offsetof(Struct, Struct::_m8), \
		offsetof(Struct, Struct::_m9), \
		offsetof(Struct, Struct::_m10), \
		offsetof(Struct, Struct::_m11), \
		offsetof(Struct, Struct::_m12), \
		offsetof(Struct, Struct::_m13), \
	}))


#define STRUCT_MEMBER_OFFSETS_15(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12, _m13, _n13, _m14, _n14) \
	std::move(std::vector<size_t>(\
	{\
		offsetof(Struct, Struct::_m0), \
		offsetof(Struct, Struct::_m1), \
		offsetof(Struct, Struct::_m2), \
		offsetof(Struct, Struct::_m3), \
		offsetof(Struct, Struct::_m4), \
		offsetof(Struct, Struct::_m5), \
		offsetof(Struct, Struct::_m6), \
		offsetof(Struct, Struct::_m7), \
		offsetof(Struct, Struct::_m8), \
		offsetof(Struct, Struct::_m9), \
		offsetof(Struct, Struct::_m10), \
		offsetof(Struct, Struct::_m11), \
		offsetof(Struct, Struct::_m12), \
		offsetof(Struct, Struct::_m13), \
		offsetof(Struct, Struct::_m14), \
	}))


#define STRUCT_MEMBER_OFFSETS_16(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12, _m13, _n13, _m14, _n14, _m15, _n15) \
	std::move(std::vector<size_t>(\
	{\
		offsetof(Struct, Struct::_m0), \
		offsetof(Struct, Struct::_m1), \
		offsetof(Struct, Struct::_m2), \
		offsetof(Struct, Struct::_m3), \
		offsetof(Struct, Struct::_m4), \
		offsetof(Struct, Struct::_m5), \
		offsetof(Struct, Struct::_m6), \
		offsetof(Struct, Struct::_m7), \
		offsetof(Struct, Struct::_m8), \
		offsetof(Struct, Struct::_m9), \
		offsetof(Struct, Struct::_m10), \
		offsetof(Struct, Struct::_m11), \
		offsetof(Struct, Struct::_m12), \
		offsetof(Struct, Struct::_m13), \
		offsetof(Struct, Struct::_m14), \
		offsetof(Struct, Struct::_m15), \
	}))


#define STRUCT_MEMBER_NAMES_1(Struct, _m0, _n0) \
	std::move(std::vector<std::string>(\
	{\
		_n0, \
	}))


#define STRUCT_MEMBER_NAMES_2(Struct, _m0, _n0, _m1, _n1) \
	std::move(std::vector<std::string>(\
	{\
		_n0, \
		_n1, \
	}))


#define STRUCT_MEMBER_NAMES_3(Struct, _m0, _n0, _m1, _n1, _m2, _n2) \
	std::move(std::vector<std::string>(\
	{\
		_n0, \
		_n1, \
		_n2, \
	}))


#define STRUCT_MEMBER_NAMES_4(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3) \
	std::move(std::vector<std::string>(\
	{\
		_n0, \
		_n1, \
		_n2, \
		_n3, \
	}))


#define STRUCT_MEMBER_NAMES_5(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4) \
	std::move(std::vector<std::string>(\
	{\
		_n0, \
		_n1, \
		_n2, \
		_n3, \
		_n4, \
	}))


#define STRUCT_MEMBER_NAMES_6(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5) \
	std::move(std::vector<std::string>(\
	{\
		_n0, \
		_n1, \
		_n2, \
		_n3, \
		_n4, \
		_n5, \
	}))


#define STRUCT_MEMBER_NAMES_7(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6) \
	std::move(std::vector<std::string>(\
	{\
		_n0, \
		_n1, \
		_n2, \
		_n3, \
		_n4, \
		_n5, \
		_n6, \
	}))


#define STRUCT_MEMBER_NAMES_8(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7) \
	std::move(std::vector<std::string>(\
	{\
		_n0, \
		_n1, \
		_n2, \
		_n3, \
		_n4, \
		_n5, \
		_n6, \
		_n7, \
	}))


#define STRUCT_MEMBER_NAMES_9(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8) \
	std::move(std::vector<std::string>(\
	{\
		_n0, \
		_n1, \
		_n2, \
		_n3, \
		_n4, \
		_n5, \
		_n6, \
		_n7, \
		_n8, \
	}))


#define STRUCT_MEMBER_NAMES_10(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9) \
	std::move(std::vector<std::string>(\
	{\
		_n0, \
		_n1, \
		_n2, \
		_n3, \
		_n4, \
		_n5, \
		_n6, \
		_n7, \
		_n8, \
		_n9, \
	}))


#define STRUCT_MEMBER_NAMES_11(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10) \
	std::move(std::vector<std::string>(\
	{\
		_n0, \
		_n1, \
		_n2, \
		_n3, \
		_n4, \
		_n5, \
		_n6, \
		_n7, \
		_n8, \
		_n9, \
		_n10, \
	}))


#define STRUCT_MEMBER_NAMES_12(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11) \
	std::move(std::vector<std::string>(\
	{\
		_n0, \
		_n1, \
		_n2, \
		_n3, \
		_n4, \
		_n5, \
		_n6, \
		_n7, \
		_n8, \
		_n9, \
		_n10, \
		_n11, \
	}))


#define STRUCT_MEMBER_NAMES_13(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12) \
	std::move(std::vector<std::string>(\
	{\
		_n0, \
		_n1, \
		_n2, \
		_n3, \
		_n4, \
		_n5, \
		_n6, \
		_n7, \
		_n8, \
		_n9, \
		_n10, \
		_n11, \
		_n12, \
	}))


#define STRUCT_MEMBER_NAMES_14(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12, _m13, _n13) \
	std::move(std::vector<std::string>(\
	{\
		_n0, \
		_n1, \
		_n2, \
		_n3, \
		_n4, \
		_n5, \
		_n6, \
		_n7, \
		_n8, \
		_n9, \
		_n10, \
		_n11, \
		_n12, \
		_n13, \
	}))


#define STRUCT_MEMBER_NAMES_15(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12, _m13, _n13, _m14, _n14) \
	std::move(std::vector<std::string>(\
	{\
		_n0, \
		_n1, \
		_n2, \
		_n3, \
		_n4, \
		_n5, \
		_n6, \
		_n7, \
		_n8, \
		_n9, \
		_n10, \
		_n11, \
		_n12, \
		_n13, \
		_n14, \
	}))


#define STRUCT_MEMBER_NAMES_16(Struct, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12, _m13, _n13, _m14, _n14, _m15, _n15) \
	std::move(std::vector<std::string>(\
	{\
		_n0, \
		_n1, \
		_n2, \
		_n3, \
		_n4, \
		_n5, \
		_n6, \
		_n7, \
		_n8, \
		_n9, \
		_n10, \
		_n11, \
		_n12, \
		_n13, \
		_n14, \
		_n15, \
	}))


#define REGISTER_MEMBERS_1(name, _m0, _n0)\
	friend class NativeComponent<ComponentType>;\
	friend class AssetManager;\
	static std::vector<VirtualType::Type> getMemberTypes()\
	{\
		return STRUCT_MEMBER_TYPES_1(ComponentType, _m0, _n0);\
	}\
	static std::vector<size_t> getMemberOffsets()\
	{\
		return STRUCT_MEMBER_OFFSETS_1(ComponentType, _m0, _n0);\
	}\
	static std::vector<std::string> getMemberNames()\
	{\
		return STRUCT_MEMBER_NAMES_1(ComponentType, _m0, _n0);\
	}\
	static const char* getComponentName()\
	{\
	    return name;\
	}
	
	
	#define REGISTER_MEMBERS_2(name, _m0, _n0, _m1, _n1)\
	friend class NativeComponent<ComponentType>;\
	friend class AssetManager;\
	static std::vector<VirtualType::Type> getMemberTypes()\
	{\
		return STRUCT_MEMBER_TYPES_2(ComponentType, _m0, _n0, _m1, _n1);\
	}\
	static std::vector<size_t> getMemberOffsets()\
	{\
		return STRUCT_MEMBER_OFFSETS_2(ComponentType, _m0, _n0, _m1, _n1);\
	}\
	static std::vector<std::string> getMemberNames()\
	{\
		return STRUCT_MEMBER_NAMES_2(ComponentType, _m0, _n0, _m1, _n1);\
	}\
	static const char* getComponentName()\
	{\
	    return name;\
	}
	
	
	#define REGISTER_MEMBERS_3(name, _m0, _n0, _m1, _n1, _m2, _n2)\
	friend class NativeComponent<ComponentType>;\
	friend class AssetManager;\
	static std::vector<VirtualType::Type> getMemberTypes()\
	{\
		return STRUCT_MEMBER_TYPES_3(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2);\
	}\
	static std::vector<size_t> getMemberOffsets()\
	{\
		return STRUCT_MEMBER_OFFSETS_3(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2);\
	}\
	static std::vector<std::string> getMemberNames()\
	{\
		return STRUCT_MEMBER_NAMES_3(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2);\
	}\
	static const char* getComponentName()\
	{\
	    return name;\
	}
	
	
	#define REGISTER_MEMBERS_4(name, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3)\
	friend class NativeComponent<ComponentType>;\
	friend class AssetManager;\
	static std::vector<VirtualType::Type> getMemberTypes()\
	{\
		return STRUCT_MEMBER_TYPES_4(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3);\
	}\
	static std::vector<size_t> getMemberOffsets()\
	{\
		return STRUCT_MEMBER_OFFSETS_4(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3);\
	}\
	static std::vector<std::string> getMemberNames()\
	{\
		return STRUCT_MEMBER_NAMES_4(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3);\
	}\
	static const char* getComponentName()\
	{\
	    return name;\
	}
	
	
	#define REGISTER_MEMBERS_5(name, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4)\
	friend class NativeComponent<ComponentType>;\
	friend class AssetManager;\
	static std::vector<VirtualType::Type> getMemberTypes()\
	{\
		return STRUCT_MEMBER_TYPES_5(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4);\
	}\
	static std::vector<size_t> getMemberOffsets()\
	{\
		return STRUCT_MEMBER_OFFSETS_5(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4);\
	}\
	static std::vector<std::string> getMemberNames()\
	{\
		return STRUCT_MEMBER_NAMES_5(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4);\
	}\
	static const char* getComponentName()\
	{\
	    return name;\
	}
	
	
	#define REGISTER_MEMBERS_6(name, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5)\
	friend class NativeComponent<ComponentType>;\
	friend class AssetManager;\
	static std::vector<VirtualType::Type> getMemberTypes()\
	{\
		return STRUCT_MEMBER_TYPES_6(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5);\
	}\
	static std::vector<size_t> getMemberOffsets()\
	{\
		return STRUCT_MEMBER_OFFSETS_6(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5);\
	}\
	static std::vector<std::string> getMemberNames()\
	{\
		return STRUCT_MEMBER_NAMES_6(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5);\
	}\
	static const char* getComponentName()\
	{\
	    return name;\
	}
	
	
	#define REGISTER_MEMBERS_7(name, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6)\
	friend class NativeComponent<ComponentType>;\
	friend class AssetManager;\
	static std::vector<VirtualType::Type> getMemberTypes()\
	{\
		return STRUCT_MEMBER_TYPES_7(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6);\
	}\
	static std::vector<size_t> getMemberOffsets()\
	{\
		return STRUCT_MEMBER_OFFSETS_7(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6);\
	}\
	static std::vector<std::string> getMemberNames()\
	{\
		return STRUCT_MEMBER_NAMES_7(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6);\
	}\
	static const char* getComponentName()\
	{\
	    return name;\
	}
	
	
	#define REGISTER_MEMBERS_8(name, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7)\
	friend class NativeComponent<ComponentType>;\
	friend class AssetManager;\
	static std::vector<VirtualType::Type> getMemberTypes()\
	{\
		return STRUCT_MEMBER_TYPES_8(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7);\
	}\
	static std::vector<size_t> getMemberOffsets()\
	{\
		return STRUCT_MEMBER_OFFSETS_8(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7);\
	}\
	static std::vector<std::string> getMemberNames()\
	{\
		return STRUCT_MEMBER_NAMES_8(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7);\
	}\
	static const char* getComponentName()\
	{\
	    return name;\
	}
	
	
	#define REGISTER_MEMBERS_9(name, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8)\
	friend class NativeComponent<ComponentType>;\
	friend class AssetManager;\
	static std::vector<VirtualType::Type> getMemberTypes()\
	{\
		return STRUCT_MEMBER_TYPES_9(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8);\
	}\
	static std::vector<size_t> getMemberOffsets()\
	{\
		return STRUCT_MEMBER_OFFSETS_9(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8);\
	}\
	static std::vector<std::string> getMemberNames()\
	{\
		return STRUCT_MEMBER_NAMES_9(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8);\
	}\
	static const char* getComponentName()\
	{\
	    return name;\
	}
	
	
	#define REGISTER_MEMBERS_10(name, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9)\
	friend class NativeComponent<ComponentType>;\
	friend class AssetManager;\
	static std::vector<VirtualType::Type> getMemberTypes()\
	{\
		return STRUCT_MEMBER_TYPES_10(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9);\
	}\
	static std::vector<size_t> getMemberOffsets()\
	{\
		return STRUCT_MEMBER_OFFSETS_10(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9);\
	}\
	static std::vector<std::string> getMemberNames()\
	{\
		return STRUCT_MEMBER_NAMES_10(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9);\
	}\
	static const char* getComponentName()\
	{\
	    return name;\
	}
	
	
	#define REGISTER_MEMBERS_11(name, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10)\
	friend class NativeComponent<ComponentType>;\
	friend class AssetManager;\
	static std::vector<VirtualType::Type> getMemberTypes()\
	{\
		return STRUCT_MEMBER_TYPES_11(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10);\
	}\
	static std::vector<size_t> getMemberOffsets()\
	{\
		return STRUCT_MEMBER_OFFSETS_11(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10);\
	}\
	static std::vector<std::string> getMemberNames()\
	{\
		return STRUCT_MEMBER_NAMES_11(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10);\
	}\
	static const char* getComponentName()\
	{\
	    return name;\
	}
	
	
	#define REGISTER_MEMBERS_12(name, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11)\
	friend class NativeComponent<ComponentType>;\
	friend class AssetManager;\
	static std::vector<VirtualType::Type> getMemberTypes()\
	{\
		return STRUCT_MEMBER_TYPES_12(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11);\
	}\
	static std::vector<size_t> getMemberOffsets()\
	{\
		return STRUCT_MEMBER_OFFSETS_12(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11);\
	}\
	static std::vector<std::string> getMemberNames()\
	{\
		return STRUCT_MEMBER_NAMES_12(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11);\
	}\
	static const char* getComponentName()\
	{\
	    return name;\
	}
	
	
	#define REGISTER_MEMBERS_13(name, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12)\
	friend class NativeComponent<ComponentType>;\
	friend class AssetManager;\
	static std::vector<VirtualType::Type> getMemberTypes()\
	{\
		return STRUCT_MEMBER_TYPES_13(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12);\
	}\
	static std::vector<size_t> getMemberOffsets()\
	{\
		return STRUCT_MEMBER_OFFSETS_13(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12);\
	}\
	static std::vector<std::string> getMemberNames()\
	{\
		return STRUCT_MEMBER_NAMES_13(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12);\
	}\
	static const char* getComponentName()\
	{\
	    return name;\
	}
	
	
	#define REGISTER_MEMBERS_14(name, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12, _m13, _n13)\
	friend class NativeComponent<ComponentType>;\
	friend class AssetManager;\
	static std::vector<VirtualType::Type> getMemberTypes()\
	{\
		return STRUCT_MEMBER_TYPES_14(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12, _m13, _n13);\
	}\
	static std::vector<size_t> getMemberOffsets()\
	{\
		return STRUCT_MEMBER_OFFSETS_14(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12, _m13, _n13);\
	}\
	static std::vector<std::string> getMemberNames()\
	{\
		return STRUCT_MEMBER_NAMES_14(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12, _m13, _n13);\
	}\
	static const char* getComponentName()\
	{\
	    return name;\
	}
	
	
	#define REGISTER_MEMBERS_15(name, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12, _m13, _n13, _m14, _n14)\
	friend class NativeComponent<ComponentType>;\
	friend class AssetManager;\
	static std::vector<VirtualType::Type> getMemberTypes()\
	{\
		return STRUCT_MEMBER_TYPES_15(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12, _m13, _n13, _m14, _n14);\
	}\
	static std::vector<size_t> getMemberOffsets()\
	{\
		return STRUCT_MEMBER_OFFSETS_15(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12, _m13, _n13, _m14, _n14);\
	}\
	static std::vector<std::string> getMemberNames()\
	{\
		return STRUCT_MEMBER_NAMES_15(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12, _m13, _n13, _m14, _n14);\
	}\
	static const char* getComponentName()\
	{\
	    return name;\
	}
	
	
	#define REGISTER_MEMBERS_16(name, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12, _m13, _n13, _m14, _n14, _m15, _n15)\
	friend class NativeComponent<ComponentType>;\
	friend class AssetManager;\
	static std::vector<VirtualType::Type> getMemberTypes()\
	{\
		return STRUCT_MEMBER_TYPES_16(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12, _m13, _n13, _m14, _n14, _m15, _n15);\
	}\
	static std::vector<size_t> getMemberOffsets()\
	{\
		return STRUCT_MEMBER_OFFSETS_16(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12, _m13, _n13, _m14, _n14, _m15, _n15);\
	}\
	static std::vector<std::string> getMemberNames()\
	{\
		return STRUCT_MEMBER_NAMES_16(ComponentType, _m0, _n0, _m1, _n1, _m2, _n2, _m3, _n3, _m4, _n4, _m5, _n5, _m6, _n6, _m7, _n7, _m8, _n8, _m9, _n9, _m10, _n10, _m11, _n11, _m12, _n12, _m13, _n13, _m14, _n14, _m15, _n15);\
	}\
	static const char* getComponentName()\
	{\
	    return name;\
	}
	
	
	#define REGISTER_MEMBERS_0(name)\
	friend class NativeComponent<ComponentType>;\
	friend class AssetManager;\
	static std::vector<VirtualType::Type> getMemberTypes()\
	{\
		return {};\
	}\
	static std::vector<size_t> getMemberOffsets()\
	{\
		return {};\
	}\
	static std::vector<std::string> getMemberNames()\
	{\
		return {};\
	}\
	static const char* getComponentName()\
	{\
	    return name;\
	}
	
	
	